# Generated by Django 4.1.3 on 2022-11-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='author_id',
            new_name='author',
        ),
    ]
