# Generated by Django 4.1.3 on 2022-11-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_author_id_image_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='alt',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
